using BTD_Mod_Helper.Api.Bloons;
using Il2CppAssets.Scripts.Models.Bloons;

namespace BTD6Rogue.Bosses.Bloonarius;

public class PoppableRogueBloonarius1 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Poppable", 0); } }
public class PoppableRogueBloonarius2 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Poppable", 1); } }
public class PoppableRogueBloonarius3 : ModBloon { public override string BaseBloon => "Bloonarius2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Poppable", 2); } }
public class PoppableRogueBloonarius4 : ModBloon { public override string BaseBloon => "Bloonarius3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Poppable", 3); } }
public class PoppableRogueBloonarius5 : ModBloon { public override string BaseBloon => "Bloonarius4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Poppable", 4); } }
public class PoppableRogueBloonarius6 : ModBloon { public override string BaseBloon => "Bloonarius5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Poppable", 5); } }
public class EasyRogueBloonarius1 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Easy", 0); } }
public class EasyRogueBloonarius2 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Easy", 1); } }
public class EasyRogueBloonarius3 : ModBloon { public override string BaseBloon => "Bloonarius2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Easy", 2); } }
public class EasyRogueBloonarius4 : ModBloon { public override string BaseBloon => "Bloonarius3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Easy", 3); } }
public class EasyRogueBloonarius5 : ModBloon { public override string BaseBloon => "Bloonarius4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Easy", 4); } }
public class EasyRogueBloonarius6 : ModBloon { public override string BaseBloon => "Bloonarius5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Easy", 5); } }
public class MediumRogueBloonarius1 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Medium", 0); } }
public class MediumRogueBloonarius2 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Medium", 1); } }
public class MediumRogueBloonarius3 : ModBloon { public override string BaseBloon => "Bloonarius2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Medium", 2); } }
public class MediumRogueBloonarius4 : ModBloon { public override string BaseBloon => "Bloonarius3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Medium", 3); } }
public class MediumRogueBloonarius5 : ModBloon { public override string BaseBloon => "Bloonarius4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Medium", 4); } }
public class MediumRogueBloonarius6 : ModBloon { public override string BaseBloon => "Bloonarius5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Medium", 5); } }
public class HardRogueBloonarius1 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Hard", 0); } }
public class HardRogueBloonarius2 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Hard", 1); } }
public class HardRogueBloonarius3 : ModBloon { public override string BaseBloon => "Bloonarius2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Hard", 2); } }
public class HardRogueBloonarius4 : ModBloon { public override string BaseBloon => "Bloonarius3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Hard", 3); } }
public class HardRogueBloonarius5 : ModBloon { public override string BaseBloon => "Bloonarius4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Hard", 4); } }
public class HardRogueBloonarius6 : ModBloon { public override string BaseBloon => "Bloonarius5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Hard", 5); } }
public class ImpoppableRogueBloonarius1 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Impoppable", 0); } }
public class ImpoppableRogueBloonarius2 : ModBloon { public override string BaseBloon => "Bloonarius1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Impoppable", 1); } }
public class ImpoppableRogueBloonarius3 : ModBloon { public override string BaseBloon => "Bloonarius2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Impoppable", 2); } }
public class ImpoppableRogueBloonarius4 : ModBloon { public override string BaseBloon => "Bloonarius3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Impoppable", 3); } }
public class ImpoppableRogueBloonarius5 : ModBloon { public override string BaseBloon => "Bloonarius4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Impoppable", 4); } }
public class ImpoppableRogueBloonarius6 : ModBloon { public override string BaseBloon => "Bloonarius5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { BloonariusConfig.ApplyBloonariusSettings(bloonModel, "Impoppable", 5); } }

