using System.Collections.Generic;

namespace BTD6Rogue;

public static class MapUtil {

    public static readonly List<string> waterMaps = new List<string> {
        "TownCentre",
        "MiddleOfTheRoad",
        "OneTwoTree",
        "TheCabin",
        "Resort",
        "Skates",
        "LotusIsland",
        "CandyFalls",
        "WinterPark",
        "Carved",
        "ParkPath",
        "FrozenOver",
        "InTheLoop",
        "Cubism",
        "FourCircles",
        "EndOfTheRoad",
        "Logs",
        "Polyphemus",
        "CoveredGarden",
        "Quarry",
        "QuietStreet",
        "BloonariusPrime",
        "Balance",
        "Encrypted",
        "Bazaar",
        "AdorasTemple",
        "SpringSpring",
        "Haunted",
        "Downstream",
        "FiringRange",
        "Cracked",
        "Streambed",
        "Chutes",
        "Rake",
        "SpiceIslands",
        "Erosion",
        "SunkenColumns",
        "Spillway",
        "Cargo",
        "PatsPond",
        "Peninsula",
        "HighFinance",
        "AnotherBrick",
        "OffTheCoast",
        "DarkDungeons",
        "Sanctuary",
        "Ravine",
        "FloodedValley",
        "Infernal",
        "BloodyPuddles",
        "Quad",
        "DarkCastle",
        "MuddyPuddles",
        "#ouch",
    };
}