using BTD_Mod_Helper.Api.Bloons;
using Il2CppAssets.Scripts.Models.Bloons;

namespace BTD6Rogue.Bosses.Dreadbloon;

public class PoppableRogueDreadbloon1 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Poppable", 0); } }
public class PoppableRogueDreadbloon2 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Poppable", 1); } }
public class PoppableRogueDreadbloon3 : ModBloon { public override string BaseBloon => "Dreadbloon2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Poppable", 2); } }
public class PoppableRogueDreadbloon4 : ModBloon { public override string BaseBloon => "Dreadbloon3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Poppable", 3); } }
public class PoppableRogueDreadbloon5 : ModBloon { public override string BaseBloon => "Dreadbloon4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Poppable", 4); } }
public class PoppableRogueDreadbloon6 : ModBloon { public override string BaseBloon => "Dreadbloon5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Poppable", 5); } }
public class EasyRogueDreadbloon1 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Easy", 0); } }
public class EasyRogueDreadbloon2 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Easy", 1); } }
public class EasyRogueDreadbloon3 : ModBloon { public override string BaseBloon => "Dreadbloon2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Easy", 2); } }
public class EasyRogueDreadbloon4 : ModBloon { public override string BaseBloon => "Dreadbloon3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Easy", 3); } }
public class EasyRogueDreadbloon5 : ModBloon { public override string BaseBloon => "Dreadbloon4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Easy", 4); } }
public class EasyRogueDreadbloon6 : ModBloon { public override string BaseBloon => "Dreadbloon5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Easy", 5); } }
public class MediumRogueDreadbloon1 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Medium", 0); } }
public class MediumRogueDreadbloon2 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Medium", 1); } }
public class MediumRogueDreadbloon3 : ModBloon { public override string BaseBloon => "Dreadbloon2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Medium", 2); } }
public class MediumRogueDreadbloon4 : ModBloon { public override string BaseBloon => "Dreadbloon3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Medium", 3); } }
public class MediumRogueDreadbloon5 : ModBloon { public override string BaseBloon => "Dreadbloon4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Medium", 4); } }
public class MediumRogueDreadbloon6 : ModBloon { public override string BaseBloon => "Dreadbloon5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Medium", 5); } }
public class HardRogueDreadbloon1 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Hard", 0); } }
public class HardRogueDreadbloon2 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Hard", 1); } }
public class HardRogueDreadbloon3 : ModBloon { public override string BaseBloon => "Dreadbloon2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Hard", 2); } }
public class HardRogueDreadbloon4 : ModBloon { public override string BaseBloon => "Dreadbloon3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Hard", 3); } }
public class HardRogueDreadbloon5 : ModBloon { public override string BaseBloon => "Dreadbloon4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Hard", 4); } }
public class HardRogueDreadbloon6 : ModBloon { public override string BaseBloon => "Dreadbloon5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Hard", 5); } }
public class ImpoppableRogueDreadbloon1 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Impoppable", 0); } }
public class ImpoppableRogueDreadbloon2 : ModBloon { public override string BaseBloon => "Dreadbloon1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Impoppable", 1); } }
public class ImpoppableRogueDreadbloon3 : ModBloon { public override string BaseBloon => "Dreadbloon2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Impoppable", 2); } }
public class ImpoppableRogueDreadbloon4 : ModBloon { public override string BaseBloon => "Dreadbloon3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Impoppable", 3); } }
public class ImpoppableRogueDreadbloon5 : ModBloon { public override string BaseBloon => "Dreadbloon4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Impoppable", 4); } }
public class ImpoppableRogueDreadbloon6 : ModBloon { public override string BaseBloon => "Dreadbloon5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadbloonConfig.ApplyDreadbloonSettings(bloonModel, "Impoppable", 5); } }