using BTD_Mod_Helper.Api.Bloons;
using Il2CppAssets.Scripts.Models.Bloons;

namespace BTD6Rogue.Bosses.Dreadbloon;

public class PoppableRogueDreadRock1 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Poppable", 0); } }
public class PoppableRogueDreadRock2 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Poppable", 1); } }
public class PoppableRogueDreadRock3 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Poppable", 2); } }
public class PoppableRogueDreadRock4 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Poppable", 3); } }
public class PoppableRogueDreadRock5 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Poppable", 4); } }
public class PoppableRogueDreadRock6 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Poppable", 5); } }
public class EasyRogueDreadRock1 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Easy", 0); } }
public class EasyRogueDreadRock2 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Easy", 1); } }
public class EasyRogueDreadRock3 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Easy", 2); } }
public class EasyRogueDreadRock4 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Easy", 3); } }
public class EasyRogueDreadRock5 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Easy", 4); } }
public class EasyRogueDreadRock6 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Easy", 5); } }
public class MediumRogueDreadRock1 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Medium", 0); } }
public class MediumRogueDreadRock2 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Medium", 1); } }
public class MediumRogueDreadRock3 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Medium", 2); } }
public class MediumRogueDreadRock4 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Medium", 3); } }
public class MediumRogueDreadRock5 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Medium", 4); } }
public class MediumRogueDreadRock6 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Medium", 5); } }
public class HardRogueDreadRock1 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Hard", 0); } }
public class HardRogueDreadRock2 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Hard", 1); } }
public class HardRogueDreadRock3 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Hard", 2); } }
public class HardRogueDreadRock4 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Hard", 3); } }
public class HardRogueDreadRock5 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Hard", 4); } }
public class HardRogueDreadRock6 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Hard", 5); } }
public class ImpoppableRogueDreadRock1 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Impoppable", 0); } }
public class ImpoppableRogueDreadRock2 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard1"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Impoppable", 1); } }
public class ImpoppableRogueDreadRock3 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard2"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Impoppable", 2); } }
public class ImpoppableRogueDreadRock4 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard3"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Impoppable", 3); } }
public class ImpoppableRogueDreadRock5 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard4"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Impoppable", 4); } }
public class ImpoppableRogueDreadRock6 : ModBloon { public override string BaseBloon => "DreadRockBloonStandard5"; public override void ModifyBaseBloonModel(BloonModel bloonModel) { DreadRockConfig.ApplyDreadRockSettings(bloonModel, "Impoppable", 5); } }