using BTD_Mod_Helper.Api;
using System.Collections.Generic;

namespace BTD6Rogue;

public abstract class RogueMap : NamedModContent {
    public abstract string MapName { get; }
    public abstract bool HasWater { get; }
    public abstract float TrackLength { get; }
    public abstract int MapDifficulty { get; }

    public static readonly Dictionary<string, float> mapLengths = new Dictionary<string, float> {
        ["Tutorial"] = 32.75f, // Monkey Meadow
        ["TreeStump"] = 44.27f,
        ["TownCenter"] = 34.65f,
        ["MiddleOfTheRoad"] = 45.2f,
        ["OneTwoTree"] = 43,
        ["Scrapyard"] = 60.73f,
        ["TheCabin"] = 34.47f,
        ["Resort"] = 54.33f,
        ["Skates"] = 42.98f,
        ["LotusIsland"] = 37.2f,
        ["CandyFalls"] = 47.92f,
        ["WinterPark"] = 41.05f,
        ["Carved"] = 44.67f,
        ["ParkPath"] = 40.22f,
        ["AlpineRun"] = 36.55f,
        ["FrozenOver"] = 40.37f,
        ["InTheLoop"] = 44.39f,
        ["Cubism"] = 49.22f,
        ["FourCircles"] = 41.42f,
        ["Hedge"] = 43.78f,
        ["EndOfTheRoad"] = 30.05f,
        ["Logs"] = 60.33f,
        ["Polyphemus"] = 21.94f,
        ["CoveredGarden"] = 19.7f,
        ["Quarry"] = 37.4f,
        ["QuietStreet"] = 28.89f,
        ["BloonariusPrime"] = 19.64f,
        ["Balance"] = 27.17f,
        ["Encrypted"] = 32.77f,
        ["Bazaar"] = 23.18f,
        ["AdorasTemple"] = 31.6f,
        ["SpringSpring"] = 28,
        ["KartsNDarts"] = 37.14f,
        ["MoonLanding"] = 40.37f,
        ["Haunted"] = 21.14f,
        ["Downstream"] = 29.97f,
        ["FiringRange"] = 33.67f,
        ["Cracked"] = 37.77f,
        ["Streambed"] = 30.8f,
        ["Chutes"] = 17.21f,
        ["Rake"] = 17.75f,
        ["SpiceIslands"] = 27.1f,
        ["Erosion"] = 6.41f,
        ["MidnightMansion"] = 19,
        ["SunkenColumns"] = 18.8f,
        ["XFactor"] = 17.38f,
        ["Mesa"] = 12.49f,
        ["Geared"] = 15.79f,
        ["Spillway"] = 25.3f,
        ["Cargo"] = 13.45f,
        ["PatsPond"] = 15.6f,
        ["Peninsula"] = 16.16f,
        ["HighFinance"] = 17.63f,
        ["AnotherBrick"] = 22.31f,
        ["OffTheCoast"] = 21.97f,
        ["Cornfield"] = 27.39f,
        ["Underground"] = 14.44f,
        ["DarkDungeons"] = 11.72f,
        ["Sanctuary"] = 12.42f,
        ["Ravine"] = 9.01f,
        ["FloodedValley"] = 10.12f,
        ["Infernal"] = 21.95f,
        ["BloodyPuddles"] = 10.1f,
        ["Workshop"] = 6.71f,
        ["Quad"] = 12.68f,
        ["Dark Castle"] = 10.39f,
        ["Muddy Puddles"] = 10.87f,
        ["#ouch"] = 4.52f,
        ["Blons"] = 4.22f,
    };

    public static readonly List<string> waterMaps = new List<string> {
        "TownCentre",
        "MiddleOfTheRoad",
        "OneTwoTree",
        "TheCabin",
        "Resort",
        "Skates",
        "LotusIsland",
        "CandyFalls",
        "WinterPark",
        "Carved",
        "ParkPath",
        "FrozenOver",
        "InTheLoop",
        "Cubism",
        "FourCircles",
        "EndOfTheRoad",
        "Logs",
        "Polyphemus",
        "CoveredGarden",
        "Quarry",
        "QuietStreet",
        "BloonariusPrime",
        "Balance",
        "Encrypted",
        "Bazaar",
        "AdorasTemple",
        "SpringSpring",
        "Haunted",
        "Downstream",
        "FiringRange",
        "Cracked",
        "Streambed",
        "Chutes",
        "Rake",
        "SpiceIslands",
        "Erosion",
        "SunkenColumns",
        "Spillway",
        "Cargo",
        "PatsPond",
        "Peninsula",
        "HighFinance",
        "AnotherBrick",
        "OffTheCoast",
        "DarkDungeons",
        "Sanctuary",
        "Ravine",
        "FloodedValley",
        "Infernal",
        "BloodyPuddles",
        "Quad",
        "DarkCastle",
        "MuddyPuddles",
        "#ouch",
    };
}
